pipeline {
  agent any

  stages {
    stage('Initialize Terraform') {
      steps {
        sh 'cd Terraform/Secure_Infrastructure_Provisioning_and_CICD_Automation_with_Terraform_Azure_Vault_and_Jenkins && terraform init' 
      }
    }

    stage('Validate Format') {
      steps {
        sh 'terraform fmt'
      }
    }

    stage('Validate Terraform') {
      steps {
        sh 'terraform validate'
      }
    }

    stage('Plan Terraform') {
      steps {
        sh 'terraform plan' 
      } 
    }
  }
}
