pipeline {
    agent any

    environment {
        TF_DIR = 'Terraform/Secure_Infrastructure_Provisioning_and_CICD_Automation_with_Terraform_Azure_Vault_and_Jenkins'
    }

    stages {
        stage('Initialize Terraform') {
            steps {
                dir(env.TF_DIR) {
                    sh 'terraform init'
                }
            }
        }

        stage('Validate Format') {
            steps {
                dir(env.TF_DIR) {
                    sh 'terraform fmt'
                }
            }
        }

        stage('Validate Terraform') {
            steps {
                dir(env.TF_DIR) {
                    sh 'terraform validate'
                }
            }
        }

        stage('Plan Terraform') {
            steps {
                dir(env.TF_DIR) {
                    sh 'terraform plan'
                }
            }
        }
    }
}
